#!/bin/sh

# Create modem interface
uci set network.modem=interface
uci set network.modem.proto='modemmanager'
uci set network.modem.device='qcom-soc'
uci set network.modem.auth='none'
uci set network.modem.apn='internet'
uci set network.modem.allowedmode='4g|3g'
uci set network.modem.preferredmode='4g'
uci set network.modem.ifname='wwan0'
uci del_list firewall.@zone[1].network='modem'
uci add_list firewall.@zone[1].network='modem'

# We don't have eth0
uci -q del_list "network.@device[0].ports=eth0" 2>/dev/null || true
sed -i 's/"device": "eth0"/"device": "br-lan"/g' /etc/board.json

# Remove target-specific APK feed (msm89xx is not on downloads.openwrt.org)
sed -i '\|/targets/msm89xx/msm8916/packages|d' /etc/apk/repositories.d/distfeeds.list 2>/dev/null || true

# Enable Wi-Fi by default
uci -q set wireless.radio0.disabled='0' 2>/dev/null || true
uci -q set wireless.default_radio0.disabled='0' 2>/dev/null || true

# Set initial eps bearer to disabled for Qualcomm SoC BAM-DMUX modem
uci -q set network.modem.init_epsbearer='disabled' 2>/dev/null || true
uci -q set network.modem.apn='indosatgprs' 2>/dev/null || true
uci -q set network.modem.iptype='ipv4v6' 2>/dev/null || true

# Set Proton2025 as default LuCI theme
uci -q set luci.main.mediaurlbase='/luci-static/proton2025' 2>/dev/null || true
uci -q set luci.themes.Proton2025='/luci-static/proton2025' 2>/dev/null || true

# Symlink cascade.css fallback for standard LuCI theme loader
ln -sf /www/luci-static/proton2025/css/cascade.css /www/luci-static/proton2025/cascade.css 2>/dev/null || true

# Fix permissions on /www and ucode templates
chmod 755 /www/cgi-bin/luci 2>/dev/null || true
chmod -R 755 /www 2>/dev/null || true
find /www -type f -exec chmod 644 {} + 2>/dev/null || true
chmod 755 /www/cgi-bin/* 2>/dev/null || true
chmod -R 755 /usr/share/ucode/luci/template/themes/proton2025 2>/dev/null || true
find /usr/share/ucode/luci/template/themes/proton2025 -type f -exec chmod 644 {} + 2>/dev/null || true

uci commit


