CONFIG_LEDS_TRIGGER_NETDEV=y
CONFIG_LEDS_TRIGGER_SIMCARD=y
CONFIG_LEDS_TRIGGER_TIMER=y
CONFIG_LEDS_TRIGGER_DEFAULT_ON=y
CONFIG_LEDS_TRIGGER_HEARTBEAT=y
CONFIG_LEDS_TRIGGER_ACTIVITY=y
CONFIG_LEDS_TRIGGER_TRANSIENT=y
CONFIG_ZRAM=y
CONFIG_ZRAM_DEF_COMP_LZ4=y
