#!/bin/sh /etc/rc.common
# Следит за сессией данных: сеть могла пересоздать её с новым адресом, а netifd
# об этом не узнаёт. См. /usr/share/5gmodem/sessionwatch.sh.

START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/share/5gmodem/sessionwatch.sh
	procd_set_param respawn
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}
